
# docker-compose.yaml
version: '3.8'

services:
  ansible:
    build: .
    volumes:
      - ./automation:/automation
    working_dir: /automation
    environment:
      - ANSIBLE_CONFIG=/automation/ansible.cfg
