---
- name: Backup Cisco Router Configuration
  hosts: routers
  gather_facts: false

  tasks:
    - name: Retrieve running configuration
      ios_command:
        commands:
          - show running-config
      register: running_config

    - name: Save configuration to a local file
      copy:
        content: "{{ running_config.stdout [0] }}"
        dest: "backups/{{ inventory_hostname }}_running-config.txt"
